version: "3.3"
services:
  dochausersrv:
    build: .
    volumes:
      - /home/scanner/dochauser_mount/archive:/home/scanner/archive
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
